-- VOICE PACK NAME
FOPM_voicepack_name = "Male"

-- VOICE PACK DURATION CONFIG
-- MUST CUMON
FO_voices_directory.OFF.del = 0.382
FO_voices_directory.ON.del = 0.413
FO_voices_directory.NORMAL.del = 0.615
FO_voices_directory.CHECK.del = 0.639
-- BUMBERS
FO_voices_directory.N0.del = 0.499
FO_voices_directory.N1.del = 0.450
FO_voices_directory.N2.del = 0.403
FO_voices_directory.N3.del = 0.454
FO_voices_directory.N4.del = 0.404
FO_voices_directory.N5.del = 0.408
FO_voices_directory.N6.del = 0.403
FO_voices_directory.N7.del = 0.497
FO_voices_directory.N8.del = 0.440
FO_voices_directory.N9.del = 0.445
-- SECTION 1
FO_voices_directory.RETRACT_AND_DISARM.del = 1.528
FO_voices_directory.ARM.del = 0.393
FO_voices_directory.UP.del = 0.396
FO_voices_directory.DOWN.del = 0.591
-- SECTION 2
FO_voices_directory.FULL_UP.del = 0.669
FO_voices_directory.FULL_DOWN.del = 0.566
FO_voices_directory.NEUTRAL.del = 0.422
FO_voices_directory.FULL_LEFT.del = 0.836
FO_voices_directory.FULL_RIGHT.del = 0.852
FO_voices_directory.SET.del = 0.671
FO_voices_directory.TA_RA.del = 1.592
FO_voices_directory.IGNITION.del = 0.605
FO_voices_directory.N1_2.del = 0.827
FO_voices_directory.PUSH.del = 0.602
FO_voices_directory.AVAIL.del = 0.724
FO_voices_directory.LOW.del = 0.385
FO_voices_directory.MEDIUM.del = 0.509
FO_voices_directory.MAX.del = 0.514
-- SECTION 3
FO_voices_directory.ENGINE_MASTERS.del = 1.509
FO_voices_directory.ENGINE_MODE_SELECTOR.del = 1.685
FO_voices_directory.WEATHER_RADAR.del = 1.009
FO_voices_directory.LANDING_GEAR.del = 0.846
FO_voices_directory.WIPERS.del = 0.668
FO_voices_directory.BATTERIES.del = 0.679
FO_voices_directory.EXTERNAL_POWER.del = 1.236
FO_voices_directory.RECALL.del = 0.841
FO_voices_directory.SYSTEMS_CHECK.del = 1.044
FO_voices_directory.OXYGEN.del = 0.690
FO_voices_directory.HYDRAULICS.del = 0.686
FO_voices_directory.OIL_QUANTITY.del = 0.965
FO_voices_directory.FLAPS.del = 0.602
FO_voices_directory.SPEED_BRAKE.del = 1.063
FO_voices_directory.PARKING_BRAKE.del = 1.013
-- SECTION 4
FO_voices_directory.BRAKE_ACCUMULATOR.del = 1.186
FO_voices_directory.ALTERNATE_BRAKES.del = 0.982
FO_voices_directory.GROUND_SPOILERS.del = 1.052
FO_voices_directory.RUDDER_TRIM.del = 0.809
FO_voices_directory.PITCHTRM.del = 1.128
FO_voices_directory.FLIGHT_CONTROLS_CHECK.del = 1.117
FO_voices_directory.ELEVATOR.del = 0.962
FO_voices_directory.AILERONS.del = 0.690
FO_voices_directory.RDR.del = 0.502
FO_voices_directory.PWS.del = 0.825
FO_voices_directory.BRAKE_TEMP.del = 0.768
-- SECTION 5
FO_voices_directory.BRAKE_FAN.del = 0.778
FO_voices_directory.EXTERIOR_LIGHTS.del = 1.540
FO_voices_directory.TCAS.del = 0.738
FO_voices_directory.PACKS.del = 0.480
FO_voices_directory.STABLE.del = 0.838
FO_voices_directory.TRHUST_SET.del = 1.147
FO_voices_directory.N100.del = 0.663
FO_voices_directory.V1.del = 0.493
FO_voices_directory.ROTATE.del = 0.517
FO_voices_directory.POSITIVE_RATE.del = 1.321
FO_voices_directory.GEAR_UP.del = 0.555
FO_voices_directory.GEAR_DOWN.del = 0.696
FO_voices_directory.GEAR_3GREENS.del = 0.849
FO_voices_directory.APU_MASTER.del = 0.921
FO_voices_directory.STARTING_APU.del = 1.540
FO_voices_directory.SPEED_CHECK.del = 1.136
FO_voices_directory.TERRAIN.del = 0.825
-- SECTION 6
FO_voices_directory.SEAT_BELTS.del = 1.089
FO_voices_directory.LS.del = 0.708
FO_voices_directory.GO_ARROUND.del = 0.751
FO_voices_directory.TOGA.del = 0.645
FO_voices_directory.SPOILERS.del = 1.076
FO_voices_directory.REVERSE_GREEN.del = 0.753
FO_voices_directory.DECEL.del = 0.834
FO_voices_directory.N60_KNOTS.del = 0.712
FO_voices_directory.TRNS_ALT.del = 1.101
FO_voices_directory.TRNS_LVL.del = 0.863
FO_voices_directory.FLIGHT_DIRECTORS.del = 1.028
-- SECTION 7
FO_voices_directory.LANDING_LIGHTS.del = 0.936
FO_voices_directory.TAXI_LIGHT.del = 0.978
FO_voices_directory.APU_BLEED.del = 1.001
FO_voices_directory.FUEL_PUMPS.del = 0.738
FO_voices_directory.ENGINE1.del = 0.805
FO_voices_directory.ENGINE2.del = 0.741
FO_voices_directory.YELLOW_HYDRAULIC_PUMP.del = 1.170
FO_voices_directory.STARTING_NUMBER_2.del = 1.186
FO_voices_directory.CHECK_TIME.del = 0.749
FO_voices_directory.CROSS_BLEED.del = 0.827
FO_voices_directory.AUTOBRAKES.del = 0.840
FO_voices_directory.ENGINE_2_SHUTDOWN.del = 1.114
FO_voices_directory.ECAM_RCLL.del = 0.866
FO_voices_directory.TEN_THAUSAND_FEET.del = 1.006
-- SPECIAL PROCEDURES (AR - CAT II/III)
FO_voices_directory.NAVAIDS_DESELECTION.del = 1.236
FO_voices_directory.GPS_NAV_MODE.del = 1.072
FO_voices_directory.BOTH_NAV.del = 0.739
FO_voices_directory.ON_ON.del = 0.770
FO_voices_directory.CRONO3.del = 0.573
-- CHECKLIST ANSWER
FO_voices_directory.COMPLETED.del = 0.757
FO_voices_directory.REMOVED.del = 0.669
FO_voices_directory.ON_AUTO.del = 1.323
FO_voices_directory.NAV.del = 0.584
FO_voices_directory.CLOSE.del = 0.447
FO_voices_directory.IDLE.del = 0.479
FO_voices_directory.CONFIRM.del = 0.791
FO_voices_directory.TAKEOFF_NO_BLUE.del = 1.098
FO_voices_directory.ADVISED.del = 0.697
FO_voices_directory.MANAGE_SPEED.del = 1.035
FO_voices_directory.SELECTED_SPEED.del = 1.277
FO_voices_directory.RETRACTED.del = 0.643
FO_voices_directory.DISARMED.del = 0.727
FO_voices_directory.AUTO.del = 0.416
-- CHECKLIST 1
FO_voices_directory.BEFORE_START_CHECKLIST.del = 1.318
FO_voices_directory.EFB_PREPARATION.del = 1.581
FO_voices_directory.AIRCRAFT_PBN_CAPABILITY.del = 1.940
FO_voices_directory.COCKPIT_PREPARATION.del = 1.409
FO_voices_directory.GEAR_PINS_AND_COVERS.del = 1.516
FO_voices_directory.SIGNS.del = 0.672
FO_voices_directory.ADIRS.del = 0.793
FO_voices_directory.FUEL_QUANTITY.del = 1.036
FO_voices_directory.BARO_REFERENCE.del = 1.233
FO_voices_directory.DOWN_TO_THE_LINE.del = 0.982
-- CHECLIST 2
FO_voices_directory.BEFORE_START_CHECKLIST_BELOW_THE_LINE.del = 1.888
FO_voices_directory.EFB.del = 0.842
FO_voices_directory.ATC.del = 0.715
FO_voices_directory.WINDOWS_AND_DOORS.del = 1.215
FO_voices_directory.BEACON.del = 0.576
FO_voices_directory.THRUST_LEVERS.del = 1.093
FO_voices_directory.CHECKLIST_COMPLETED.del = 1.172
FO_voices_directory.AFTER_START_CHECKLIST.del = 1.558
FO_voices_directory.ANTI_ICE.del = 0.864
-- CHECKLIST 3
FO_voices_directory.ECAM_STATUS.del = 1.143
FO_voices_directory.BEFORE_TAKEOFF_CHECKLIST.del = 1.425
FO_voices_directory.FLIGHT_CONTROLS.del = 0.843
FO_voices_directory.FLY_INSTRUMENTS.del = 1.032
FO_voices_directory.BRIEFING.del = 0.645
FO_voices_directory.V1_VR_V2_FLEX_TEMP.del = 1.900
FO_voices_directory.ECAM_MEMO.del = 0.938
FO_voices_directory.TAKEOFF_RUNWAY.del = 1.120
FO_voices_directory.NAV_ON_FMA.del = 1.143
FO_voices_directory.CABIN_CREW.del = 0.945
-- CHECKLIST 4
FO_voices_directory.PACKS_AND_APU_BLEED.del = 1.419
FO_voices_directory.AFTER_TAKEOFF_CHECKLIST.del = 1.361
FO_voices_directory.CLIMB_CHECKLIST.del = 1.105
FO_voices_directory.APPROACH_CHECKLIST.del = 1.315
FO_voices_directory.MINIMUMS.del = 0.867
FO_voices_directory.LANDING_CHECKLIST.del = 1.175
FO_voices_directory.AUTO_TRHUST.del = 0.983
FO_voices_directory.AFTER_LANDING_CHECKLIST.del = 1.595
-- CHECKLIST 5
FO_voices_directory.PARKING_CHECKLIST.del = 1.051
FO_voices_directory.ENGINES.del = 0.777
FO_voices_directory.SECURING_CHECKLIST.del = 1.333
FO_voices_directory.EMERGENCY_EXIT_LIGHTS.del = 1.455
FO_voices_directory.NO_PORTABLE_SIGNS.del = 1.212
FO_voices_directory.APU_AND_BATTERY.del = 1.351
FO_voices_directory.BEFORE_TAKEOFF_CHECKLIST_BELOW_THE_LINE.del = 2.052
FO_voices_directory.APU.del = 0.710
-- FLIGHT PARAMETERS CALLOUTS
FO_voices_directory.SPEED.del = 0.526
FO_voices_directory.SINK_RATE.del = 0.934
FO_voices_directory.BANK.del = 0.611
FO_voices_directory.PITCH.del = 0.6
FO_voices_directory.LOC.del = 0.551
FO_voices_directory.GLIDE.del = 0.566
FO_voices_directory.CROSS_TRACK.del = 0.865
FO_voices_directory.LAT_DEV.del = 0.746
FO_voices_directory.V_DEV.del = 0.815
FO_voices_directory.GA_UNSTABLE.del = 1.319
-- AUTOLAND CALLOUTS
FO_voices_directory.LAND.del = 0.681
FO_voices_directory.FLARE.del = 0.572
FO_voices_directory.ROLL_OUT.del = 0.713

-- FLAP CONFIG DIRECTORY
FLAP_CONFIG.CP1.del = 1.288
FLAP_CONFIG.CP2.del = 0.832
FLAP_CONFIG.CP3.del = 0.892

-- FLAP POSITION DIRECTORY
FLAP_POS.P0.del = 0.886
FLAP_POS.P1.del = 0.742
FLAP_POS.P2.del = 0.756
FLAP_POS.P3.del = 0.813
FLAP_POS.FULL.del = 0.660

-- BRKAE TEMP WARNING
BRAKE_WARN[1].del = 1.937
BRAKE_WARN[2].del = 1.786
BRAKE_WARN[3].del = 1.901

-- POST BRIEFING
BRIEF_CONF[1].del = 2.034
BRIEF_CONF[2].del = 1.601
BRIEF_CONF[3].del = 1.326
BRIEF_CONF[4].del = 0.704

-- READY SPEECH
RDY[1].del = 0.635
RDY[2].del = 0.824
RDY[3].del = 0.788
RDY[4].del = 1.101
RDY[5].del = 1.207

-- READY FOR T/O
RDY_TO_DIR[1].del = 1.181
RDY_TO_DIR[2].del = 1.649
RDY_TO_DIR[3].del = 1.068