-- VOICE PACK NAME
FOPM_voicepack_name = "Adriana"

-- VOICE PACK DURATION CONFIG
-- NOT NEEDED ANY MORE.
-- SINCE V1.2 THE PLUGIN READS THE EXACT DURATION OF EVERY .wav STRAIGHT FROM
-- THE FILE ITSELF WHEN THE PACK IS LOADED, SO THERE IS NOTHING TO TYPE HERE
-- AND NOTHING TO KEEP IN SYNC WHEN YOU RE-RECORD A CALLOUT.
--
-- IF YOU EVER WANT ONE CALLOUT TO BE SPACED OUT BY SOMETHING OTHER THAN ITS
-- REAL LENGTH, YOU CAN STILL FORCE IT HERE AND IT OVERRIDES THE MEASUREMENT:
--
--     FO_voices_directory.OFF.del = 0.856
--
-- THE TIME IS IN SECONDS. LEAVE THIS SECTION EMPTY TO USE THE REAL DURATIONS.
