-- VOICE PACK NAME
FOPM_voicepack_name = "Adriana"

-- VOICE PACK DURATION CONFIG
-- MUST CUMON
FO_voices_directory.OFF.del = 0.574
FO_voices_directory.ON.del = 0.619
FO_voices_directory.NORMAL.del = 0.801
FO_voices_directory.CHECK.del = 0.643
-- NUMBERS
FO_voices_directory.N0.del = 0.595
FO_voices_directory.N1.del = 0.592
FO_voices_directory.N2.del = 0.577
FO_voices_directory.N3.del = 0.593
FO_voices_directory.N4.del = 0.648
FO_voices_directory.N5.del = 0.676
FO_voices_directory.N6.del = 0.727
FO_voices_directory.N7.del = 0.606
FO_voices_directory.N8.del = 0.484
FO_voices_directory.N9.del = 0.818
-- SECTION 1
FO_voices_directory.RETRACT_AND_DISARM.del = 1.137
FO_voices_directory.ARM.del = 0.597
FO_voices_directory.UP.del = 0.489
FO_voices_directory.DOWN.del = 0.696
-- SECTION 2
FO_voices_directory.FULL_UP.del = 0.832
FO_voices_directory.FULL_DOWN.del = 0.978
FO_voices_directory.NEUTRAL.del = 0.853
FO_voices_directory.FULL_LEFT.del = 0.771
FO_voices_directory.FULL_RIGHT.del = 0.881
FO_voices_directory.SET.del = 0.715
FO_voices_directory.TA_RA.del = 1.081
FO_voices_directory.IGNITION.del = 0.755
FO_voices_directory.AVAIL.del = 0.799
FO_voices_directory.LOW.del = 0.566
FO_voices_directory.MEDIUM.del = 0.704
FO_voices_directory.MAX.del = 0.843
-- SECTION 3
FO_voices_directory.ENGINE_MASTERS.del = 1.074
FO_voices_directory.ENGINE_MODE_SELECTOR.del = 1.358
FO_voices_directory.WEATHER_RADAR.del = 1.030
FO_voices_directory.LANDING_GEAR.del = 0.962
FO_voices_directory.WIPERS.del = 0.747
FO_voices_directory.BATTERIES.del = 0.710
FO_voices_directory.EXTERNAL_POWER.del = 1.083
FO_voices_directory.SYSTEMS_CHECK.del = 1.101
FO_voices_directory.OXYGEN.del = 0.768
FO_voices_directory.HYDRAULICS.del = 1.073
FO_voices_directory.OIL_QUANTITY.del = 1.149
FO_voices_directory.FLAPS.del = 0.668
FO_voices_directory.SPEED_BRAKE.del = 0.903
FO_voices_directory.PARKING_BRAKE.del = 0.799
-- SECTION 4
FO_voices_directory.BRAKE_ACCUMULATOR.del = 1.043
FO_voices_directory.ALTERNATE_BRAKES.del = 0.992
FO_voices_directory.GROUND_SPOILERS.del = 1.016
FO_voices_directory.RUDDER_TRIM.del = 0.846
FO_voices_directory.PITCHTRM.del = 0.773
FO_voices_directory.FLIGHT_CONTROLS_CHECK.del = 1.235
FO_voices_directory.ELEVATOR.del = 0.788
FO_voices_directory.AILERONS.del = 0.903
FO_voices_directory.RDR.del = 0.693
FO_voices_directory.PWS.del = 1.024
FO_voices_directory.BRAKE_TEMP.del = 0.852
-- SECTION 5
FO_voices_directory.BRAKE_FAN.del = 0.843
FO_voices_directory.EXTERIOR_LIGHTS.del = 1.373
FO_voices_directory.TCAS.del = 0.709
FO_voices_directory.PACKS.del = 0.674
FO_voices_directory.STABLE.del = 0.864 
FO_voices_directory.TRHUST_SET.del = 0.782
FO_voices_directory.N100.del = 0.836
FO_voices_directory.V1.del = 0.944
FO_voices_directory.ROTATE.del = 0.730
FO_voices_directory.POSITIVE_RATE.del = 1.015
FO_voices_directory.GEAR_UP.del = 0.714
FO_voices_directory.GEAR_DOWN.del = 0.944
FO_voices_directory.GEAR_3GREENS.del = 1
FO_voices_directory.APU_MASTER.del = 1.031
FO_voices_directory.STARTING_APU.del = 1.205
FO_voices_directory.SPEED_CHECK.del = 0.884
FO_voices_directory.TERRAIN.del = 0.725
-- SECTION 6
FO_voices_directory.SEAT_BELTS.del = 0.932
FO_voices_directory.LS.del = 0.731
FO_voices_directory.GO_ARROUND.del = 0.962
FO_voices_directory.TOGA.del = 0.653
FO_voices_directory.SPOILERS.del = 0.989
FO_voices_directory.REVERSE_GREEN.del = 1.209
FO_voices_directory.DECEL.del = 0.922
FO_voices_directory.N70_KNOTS.del = 0.734
FO_voices_directory.TRNS_ALT.del = 1.223
FO_voices_directory.TRNS_LVL.del = 1.076
FO_voices_directory.FLIGHT_DIRECTORS.del = 1.254
-- SECTION 7
FO_voices_directory.LANDING_LIGHTS.del = 0.949
FO_voices_directory.TAXI_LIGHT.del = 1.062
FO_voices_directory.APU_BLEED.del = 1.066
FO_voices_directory.FUEL_PUMPS.del = 0.949
FO_voices_directory.ENGINE1.del = 0.855
FO_voices_directory.ENGINE2.del = 0.884
FO_voices_directory.YELLOW_HYDRAULIC_PUMP.del = 1.695
FO_voices_directory.STARTING_NUMBER_2.del = 1.242
FO_voices_directory.CHECK_TIME.del = 0.834
FO_voices_directory.CROSS_BLEED.del = 0.826
FO_voices_directory.AUTOBRAKES.del = 0.915
FO_voices_directory.ENGINE_2_SHUTDOWN.del = 1.314
FO_voices_directory.ECAM_RCLL.del = 1.101
FO_voices_directory.TEN_THAUSAND_FEET.del = 0.966
-- SPECIAL PROCEDURES (AR - CAT II/III)
FO_voices_directory.NAVAIDS_DESELECTION.del = 1.402
FO_voices_directory.GPS_NAV_MODE.del = 1.3
FO_voices_directory.BOTH_NAV.del = 0.945
FO_voices_directory.ON_ON.del = 1.478
FO_voices_directory.CRONO3.del = 1.287
-- CHECKLIST ANSWERS
FO_voices_directory.COMPLETED.del = 0.884
FO_voices_directory.REMOVED.del = 0.693
FO_voices_directory.ON_AUTO.del = 1.291
FO_voices_directory.NAV.del = 0.569
FO_voices_directory.CLOSE.del = 0.681
FO_voices_directory.IDLE.del = 0.741
FO_voices_directory.CONFIRM.del = 0.733
FO_voices_directory.TAKEOFF_NO_BLUE.del = 1.172
FO_voices_directory.ADVISED.del = 0.911
FO_voices_directory.MANAGE_SPEED.del = 1.081
FO_voices_directory.SELECTED_SPEED.del = 1.152
FO_voices_directory.RETRACTED.del = 0.774
FO_voices_directory.DISARMED.del = 0.785
FO_voices_directory.AUTO.del = 0.646
FO_voices_directory.DESELECTED.del = 1.103
-- CHECKLIST 1
FO_voices_directory.BEFORE_START_CHECKLIST.del = 1.544
FO_voices_directory.EFB_PREPARATION.del = 1.352
FO_voices_directory.AIRCRAFT_PBN_CAPABILITY.del = 1.821
FO_voices_directory.COCKPIT_PREPARATION.del = 1.331
FO_voices_directory.GEAR_PINS_AND_COVERS.del = 1.243
FO_voices_directory.SIGNS.del = 0.742
FO_voices_directory.ADIRS.del = 0.803
FO_voices_directory.FUEL_QUANTITY.del = 0.974
FO_voices_directory.BARO_REFERENCE.del = 1.344
FO_voices_directory.DOWN_TO_THE_LINE.del = 1.039
-- CHECKLIST 2
FO_voices_directory.BEFORE_START_CHECKLIST_BELOW_THE_LINE.del = 2.324
FO_voices_directory.EFB.del = 0.855
FO_voices_directory.ATC.del = 0.919
FO_voices_directory.WINDOWS_AND_DOORS.del = 1.082
FO_voices_directory.BEACON.del = 0.620
FO_voices_directory.THRUST_LEVERS.del = 1.124
FO_voices_directory.CHECKLIST_COMPLETED.del = 1.113
FO_voices_directory.AFTER_START_CHECKLIST.del = 1.520
FO_voices_directory.ANTI_ICE.del = 1.039
-- CHECKLIST 3
FO_voices_directory.ECAM_STATUS.del = 1.188
FO_voices_directory.BEFORE_TAKEOFF_CHECKLIST.del = 1.678
FO_voices_directory.FLIGHT_CONTROLS.del = 0.954
FO_voices_directory.FLY_INSTRUMENTS.del = 1.081
FO_voices_directory.BRIEFING.del = 0.666
FO_voices_directory.V1_VR_V2_FLEX_TEMP.del = 2.238
FO_voices_directory.ECAM_MEMO.del = 1.068
FO_voices_directory.TAKEOFF_RUNWAY.del = 0.893
FO_voices_directory.NAV_ON_FMA.del = 1.560
FO_voices_directory.CABIN_CREW.del = 0.810
-- CHECKLIST 4
FO_voices_directory.PACKS_AND_APU_BLEED.del = 1.363
FO_voices_directory.AFTER_TAKEOFF_CHECKLIST.del = 1.465
FO_voices_directory.CLIMB_CHECKLIST.del = 1.323
FO_voices_directory.APPROACH_CHECKLIST.del = 1.401
FO_voices_directory.MINIMUMS.del = 0.846
FO_voices_directory.LANDING_CHECKLIST.del = 1.327
FO_voices_directory.AUTO_TRHUST.del = 1.033
FO_voices_directory.AFTER_LANDING_CHECKLIST.del = 1.505
-- CHECKLIST 5
FO_voices_directory.PARKING_CHECKLIST.del = 1.161
FO_voices_directory.ENGINES.del = 0.832
FO_voices_directory.SECURING_CHECKLIST.del = 2.033
FO_voices_directory.EMERGENCY_EXIT_LIGHTS.del = 1.367
FO_voices_directory.NO_PORTABLE_SIGNS.del = 1.223
FO_voices_directory.APU_AND_BATTERY.del = 1.348
FO_voices_directory.BEFORE_TAKEOFF_CHECKLIST_BELOW_THE_LINE.del = 2.308
FO_voices_directory.APU.del = 0.951
FO_voices_directory.COCKPIT_PREPARATION_CHECKLIST.del = 1.878
FO_voices_directory.RADIONAV_POSITION.del = 1.138
-- CHECKLIST 6
FO_voices_directory.TAKEOFF_SPEEDS_AND_THRUST.del = 1.737
FO_voices_directory.FLAPS_SETTING.del = 0.930
FO_voices_directory.RADAR_AND_PRED_WS.del = 1.776
FO_voices_directory.DEPARTURE_CHANGE_CHECKLIST.del = 1.584
FO_voices_directory.RUNWAY_AND_SID.del = 1.207
FO_voices_directory.FCU_ALTITUDE.del = 1.370
FO_voices_directory.PARKING_BRAKE_OR_CHOCKS.del = 1.440
FO_voices_directory.WING_LIGHTS.del = 0.972
FO_voices_directory.TAXI_CHECKLIST.del = 1.254
FO_voices_directory.LINEUP_CHECKLIST.del = 1.370
-- FLIGHT PARAMETERS CALLOUTS
FO_voices_directory.SPEED.del = 0.647
FO_voices_directory.SINK_RATE.del = 0.781
FO_voices_directory.BANK.del = 0.569
FO_voices_directory.PITCH.del = 0.603
FO_voices_directory.LOC.del = 0.663
FO_voices_directory.GLIDE.del = 0.665
FO_voices_directory.CROSS_TRACK.del = 0.894
FO_voices_directory.LAT_DEV.del = 0.720
FO_voices_directory.V_DEV.del = 0.751
FO_voices_directory.GA_UNSTABLE.del = 1.335
-- AUTOLAND CALLOUTS
FO_voices_directory.LAND.del = 0.797
FO_voices_directory.FLARE.del = 0.576
FO_voices_directory.ROLL_OUT.del = 0.815

-- FLAP CONFIG DIRECTORY
FLAP_CONFIG.CP1.del = 1.472
FLAP_CONFIG.CP2.del = 0.914
FLAP_CONFIG.CP3.del = 0.840

-- FLAP POSITION DIRECTORY
FLAP_POS.P0.del = 1.012
FLAP_POS.P1.del = 0.869
FLAP_POS.P2.del = 0.725
FLAP_POS.P3.del = 0.849
FLAP_POS.FULL.del = 0.839

-- BRKAE TEMP WARNING --
BRAKE_WARN[1].del = 1.943
BRAKE_WARN[2].del = 3.413
BRAKE_WARN[3].del = 2.995

-- POST BRIEFING --
BRIEF_CONF[1].del = 2.099
BRIEF_CONF[2].del = 1.892
BRIEF_CONF[3].del = 2.728
BRIEF_CONF[4].del = 2.461

-- READY SPEECH --
RDY[1].del = 1.079
RDY[2].del = 1.050
RDY[3].del = 0.974
RDY[4].del = 0.913
RDY[5].del = 2.087

-- READY FOR T/O
RDY_TO_DIR[1].del = 1.207
RDY_TO_DIR[2].del = 2.283
RDY_TO_DIR[3].del = 1.744