-- VOICE PACK NAME
FOPM_voicepack_name = "TEMPLATE"

-- VOICE PACK DURATION CONFIG
-- MUST CUMON
FO_voices_directory.OFF.del = 0
FO_voices_directory.ON.del = 0
FO_voices_directory.NORMAL.del = 0
FO_voices_directory.CHECK.del = 0
-- NUMBERS
FO_voices_directory.N0.del = 0
FO_voices_directory.N1.del = 0
FO_voices_directory.N2.del = 0
FO_voices_directory.N3.del = 0
FO_voices_directory.N4.del = 0
FO_voices_directory.N5.del = 0
FO_voices_directory.N6.del = 0
FO_voices_directory.N7.del = 0
FO_voices_directory.N8.del = 0
FO_voices_directory.N9.del = 0
-- SECTION 1
FO_voices_directory.RETRACT_AND_DISARM.del = 0
FO_voices_directory.ARM.del = 0
FO_voices_directory.UP.del = 0
FO_voices_directory.DOWN.del = 0
-- SECTION 2
FO_voices_directory.FULL_UP.del = 0
FO_voices_directory.FULL_DOWN.del = 0
FO_voices_directory.NEUTRAL.del = 0
FO_voices_directory.FULL_LEFT.del = 0
FO_voices_directory.FULL_RIGHT.del = 0
FO_voices_directory.SET.del = 0
FO_voices_directory.TA_RA.del = 0
FO_voices_directory.IGNITION.del = 0
FO_voices_directory.AVAIL.del = 0
FO_voices_directory.LOW.del = 0
FO_voices_directory.MEDIUM.del = 0
FO_voices_directory.MAX.del = 0
-- SECTION 3
FO_voices_directory.ENGINE_MASTERS.del = 0
FO_voices_directory.ENGINE_MODE_SELECTOR.del = 0
FO_voices_directory.WEATHER_RADAR.del = 0
FO_voices_directory.LANDING_GEAR.del = 0
FO_voices_directory.WIPERS.del = 0
FO_voices_directory.BATTERIES.del = 0
FO_voices_directory.EXTERNAL_POWER.del = 0
FO_voices_directory.SYSTEMS_CHECK.del = 0
FO_voices_directory.OXYGEN.del = 0
FO_voices_directory.HYDRAULICS.del = 0
FO_voices_directory.OIL_QUANTITY.del = 0
FO_voices_directory.FLAPS.del = 0
FO_voices_directory.SPEED_BRAKE.del = 0
FO_voices_directory.PARKING_BRAKE.del = 0
-- SECTION 4
FO_voices_directory.BRAKE_ACCUMULATOR.del = 0
FO_voices_directory.ALTERNATE_BRAKES.del = 0
FO_voices_directory.GROUND_SPOILERS.del = 0
FO_voices_directory.RUDDER_TRIM.del = 0
FO_voices_directory.PITCHTRM.del = 0
FO_voices_directory.FLIGHT_CONTROLS_CHECK.del = 0
FO_voices_directory.ELEVATOR.del = 0
FO_voices_directory.AILERONS.del = 0
FO_voices_directory.RDR.del = 0
FO_voices_directory.PWS.del = 0
FO_voices_directory.BRAKE_TEMP.del = 0
-- SECTION 5
FO_voices_directory.BRAKE_FAN.del = 0
FO_voices_directory.EXTERIOR_LIGHTS.del = 0
FO_voices_directory.TCAS.del = 0
FO_voices_directory.PACKS.del = 0
FO_voices_directory.STABLE.del = 0
FO_voices_directory.TRHUST_SET.del = 0
FO_voices_directory.N100.del = 0
FO_voices_directory.V1.del = 0
FO_voices_directory.ROTATE.del = 0
FO_voices_directory.POSITIVE_RATE.del = 0
FO_voices_directory.GEAR_UP.del = 0
FO_voices_directory.GEAR_DOWN.del = 0
FO_voices_directory.GEAR_3GREENS.del = 0
FO_voices_directory.APU_MASTER.del = 0
FO_voices_directory.STARTING_APU.del = 0
FO_voices_directory.SPEED_CHECK.del = 0
FO_voices_directory.TERRAIN.del = 0
-- SECTION 6
FO_voices_directory.SEAT_BELTS.del = 0
FO_voices_directory.LS.del = 0
FO_voices_directory.GO_ARROUND.del = 0
FO_voices_directory.TOGA.del = 0
FO_voices_directory.SPOILERS.del = 0
FO_voices_directory.REVERSE_GREEN.del = 0
FO_voices_directory.DECEL.del = 0
FO_voices_directory.N70_KNOTS.del = 0
FO_voices_directory.TRNS_ALT.del = 0
FO_voices_directory.TRNS_LVL.del = 0
FO_voices_directory.FLIGHT_DIRECTORS.del = 0
-- SECTION 7
FO_voices_directory.LANDING_LIGHTS.del = 0
FO_voices_directory.TAXI_LIGHT.del = 0
FO_voices_directory.APU_BLEED.del = 0
FO_voices_directory.FUEL_PUMPS.del = 0
FO_voices_directory.ENGINE1.del = 0
FO_voices_directory.ENGINE2.del = 0
FO_voices_directory.YELLOW_HYDRAULIC_PUMP.del = 0
FO_voices_directory.STARTING_NUMBER_2.del = 0
FO_voices_directory.CHECK_TIME.del = 0
FO_voices_directory.CROSS_BLEED.del = 0
FO_voices_directory.AUTOBRAKES.del = 0
FO_voices_directory.ENGINE_2_SHUTDOWN.del = 0
FO_voices_directory.ECAM_RCLL.del = 0
FO_voices_directory.TEN_THAUSAND_FEET.del = 0
-- SPECIAL PROCEDURES (AR - CAT II/III)
FO_voices_directory.NAVAIDS_DESELECTION.del = 0
FO_voices_directory.GPS_NAV_MODE.del = 0
FO_voices_directory.BOTH_NAV.del = 0
FO_voices_directory.ON_ON.del = 0
FO_voices_directory.CRONO3.del = 0
-- CHECKLIST ANSWERS
FO_voices_directory.COMPLETED.del = 0
FO_voices_directory.REMOVED.del = 0
FO_voices_directory.ON_AUTO.del = 0
FO_voices_directory.NAV.del = 0
FO_voices_directory.CLOSE.del = 0
FO_voices_directory.IDLE.del = 0
FO_voices_directory.CONFIRM.del = 0
FO_voices_directory.TAKEOFF_NO_BLUE.del = 0
FO_voices_directory.ADVISED.del = 0
FO_voices_directory.MANAGE_SPEED.del = 0
FO_voices_directory.SELECTED_SPEED.del = 0
FO_voices_directory.RETRACTED.del = 0
FO_voices_directory.DISARMED.del = 0
FO_voices_directory.AUTO.del = 0
FO_voices_directory.DESELECTED.del = 0
-- CHECKLIST 1
FO_voices_directory.BEFORE_START_CHECKLIST.del = 0
FO_voices_directory.EFB_PREPARATION.del = 0
FO_voices_directory.AIRCRAFT_PBN_CAPABILITY.del = 0
FO_voices_directory.COCKPIT_PREPARATION.del = 0
FO_voices_directory.GEAR_PINS_AND_COVERS.del = 0
FO_voices_directory.SIGNS.del = 0
FO_voices_directory.ADIRS.del = 0
FO_voices_directory.FUEL_QUANTITY.del = 0
FO_voices_directory.BARO_REFERENCE.del = 0
FO_voices_directory.DOWN_TO_THE_LINE.del = 0
-- CHECKLIST 2
FO_voices_directory.BEFORE_START_CHECKLIST_BELOW_THE_LINE.del = 0
FO_voices_directory.EFB.del = 0
FO_voices_directory.ATC.del = 0
FO_voices_directory.WINDOWS_AND_DOORS.del = 0
FO_voices_directory.BEACON.del = 0
FO_voices_directory.THRUST_LEVERS.del = 0
FO_voices_directory.CHECKLIST_COMPLETED.del = 0
FO_voices_directory.AFTER_START_CHECKLIST.del = 0
FO_voices_directory.ANTI_ICE.del = 0
-- CHECKLIST 3
FO_voices_directory.ECAM_STATUS.del = 0
FO_voices_directory.BEFORE_TAKEOFF_CHECKLIST.del = 0
FO_voices_directory.FLIGHT_CONTROLS.del = 0
FO_voices_directory.FLY_INSTRUMENTS.del = 0
FO_voices_directory.BRIEFING.del = 0
FO_voices_directory.V1_VR_V2_FLEX_TEMP.del = 0
FO_voices_directory.ECAM_MEMO.del = 0
FO_voices_directory.TAKEOFF_RUNWAY.del = 0
FO_voices_directory.NAV_ON_FMA.del = 0
FO_voices_directory.CABIN_CREW.del = 0
-- CHECKLIST 4
FO_voices_directory.PACKS_AND_APU_BLEED.del = 0
FO_voices_directory.AFTER_TAKEOFF_CHECKLIST.del = 0
FO_voices_directory.CLIMB_CHECKLIST.del = 0
FO_voices_directory.APPROACH_CHECKLIST.del = 0
FO_voices_directory.MINIMUMS.del = 0
FO_voices_directory.LANDING_CHECKLIST.del = 0
FO_voices_directory.AUTO_TRHUST.del = 0
FO_voices_directory.AFTER_LANDING_CHECKLIST.del = 0
-- CHECKLIST 5
FO_voices_directory.PARKING_CHECKLIST.del = 0
FO_voices_directory.ENGINES.del = 0
FO_voices_directory.SECURING_CHECKLIST.del = 0
FO_voices_directory.EMERGENCY_EXIT_LIGHTS.del = 0
FO_voices_directory.NO_PORTABLE_SIGNS.del = 0
FO_voices_directory.APU_AND_BATTERY.del = 0
FO_voices_directory.BEFORE_TAKEOFF_CHECKLIST_BELOW_THE_LINE.del = 0
FO_voices_directory.APU.del = 0
FO_voices_directory.COCKPIT_PREPARATION_CHECKLIST.del = 0
FO_voices_directory.RADIONAV_POSITION.del = 0
-- CHECKLIST 6
FO_voices_directory.TAKEOFF_SPEEDS_AND_THRUST.del = 0
FO_voices_directory.FLAPS_SETTING.del = 0
FO_voices_directory.RADAR_AND_PRED_WS.del = 0
FO_voices_directory.DEPARTURE_CHANGE_CHECKLIST.del = 0
FO_voices_directory.RUNWAY_AND_SID.del = 0
FO_voices_directory.FCU_ALTITUDE.del = 0
FO_voices_directory.PARKING_BRAKE_OR_CHOCKS.del = 0
FO_voices_directory.WING_LIGHTS.del = 0
FO_voices_directory.TAXI_CHECKLIST.del = 0
FO_voices_directory.LINEUP_CHECKLIST.del = 0
-- FLIGHT PARAMETERS CALLOUTS
FO_voices_directory.SPEED.del = 0
FO_voices_directory.SINK_RATE.del = 0
FO_voices_directory.BANK.del = 0
FO_voices_directory.PITCH.del = 0
FO_voices_directory.LOC.del = 0
FO_voices_directory.GLIDE.del = 0
FO_voices_directory.CROSS_TRACK.del = 0
FO_voices_directory.LAT_DEV.del = 0
FO_voices_directory.V_DEV.del = 0
FO_voices_directory.GA_UNSTABLE.del = 0
-- AUTOLAND CALLOUTS
FO_voices_directory.LAND.del = 0
FO_voices_directory.FLARE.del = 0
FO_voices_directory.ROLL_OUT.del = 0

-- FLAP CONFIG DIRECTORY
FLAP_CONFIG.CP1.del = 0
FLAP_CONFIG.CP2.del = 0
FLAP_CONFIG.CP3.del = 0

-- FLAP POSITION DIRECTORY
FLAP_POS.P0.del = 0
FLAP_POS.P1.del = 0
FLAP_POS.P2.del = 0
FLAP_POS.P3.del = 0
FLAP_POS.FULL.del = 0

-- BRKAE TEMP WARNING --
BRAKE_WARN[1].del = 0
BRAKE_WARN[2].del = 0
BRAKE_WARN[3].del = 0

-- POST BRIEFING --
BRIEF_CONF[1].del = 0
BRIEF_CONF[2].del = 0
BRIEF_CONF[3].del = 0
BRIEF_CONF[4].del = 0

-- READY SPEECH --
RDY[1].del = 0
RDY[2].del = 0
RDY[3].del = 0
RDY[4].del = 0
RDY[5].del = 0

-- READY FOR T/O
RDY_TO_DIR[1].del = 0
RDY_TO_DIR[2].del = 0
RDY_TO_DIR[3].del = 0